#include <string.h>
#include "../include/resource_handler.h"
#include "../include/http_response.h"
#include "../include/server_utils.h"

static const char home[] =
    "<!DOCTYPE html>"
    " <html lang=\"en\">"
    " <head>"
    " <meta charset=\"UTF-8\">"
    " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    " <title>Unit Converter</title>"
    " <link rel=\"stylesheet\" href=\"/src/style.css\">"
    " <script defer src=\"/src/script.js\"></script>"
    " </head>"
    " <body></body>"
    " </html>";
static const char style[] =
    "body {"
    " text-align: center;"
    " }"
    " ul {"
    " display: inline-flex;"
    " list-style: none;"
    " margin: 0 0 12px 0;"
    " padding: 1px 7px;"
    " gap: 20px;"
    " }"
    " li {"
    " cursor: pointer;"
    " padding: 3px;"
    " }"
    " p {"
    " margin: 12px 3px 5px 3px;"
    " }"
    " li:hover {"
    " color: #0000ff;"
    " }"
    " .tab_selected {"
    " color: #0000ff;"
    " border-bottom: 2px inset #0000ff;"
    " }"
    " button {"
    " width: 100px;"
    " height: 33px;"
    " }"
    " .result {"
    " font-size: 200%;"
    " margin: 12px;"
    " }"
    " .result-abr {"
    " font-size: 70%;"
    " }"
    " .error {"
    " font-size: 80%;"
    " color: #ff0000;"
    " }";
static const char script[] =
    "const home = {'body': document.body};"
    " const units = {"
    " Length: [['Millimeter', 'mm'], ['Centimeter', 'cm'], ['Meter', 'm'], ['Kilometer', 'km'], ['Inch', 'in'], ['Foot', 'ft'], ['Yard', 'yd'], ['Mile', 'mi']],"
    " Weight: [['Microgram', 'µg'], ['Milligram', 'mg'], ['Gram', 'g'], ['Kilogram', 'kg'], ['Tonne', 't'], ['Ounce', 'oz'], ['Pound', 'lb']],"
    " Temperature: [['Celsius', '°C'], ['Fahrenheit', '°F'], ['Kelvin', 'K']]"
    " };"
    " let inpValue = '';"
    " let tabSelected = '';"
    " elemCreator({"
    " 'title': ['body', 'h1', [['textContent', 'Unit Converter']]],"
    " 'nav': ['body', 'nav'],"
    " 'navList': ['nav', 'ul'],"
    " 'navLength': ['navList', 'li', [['textContent', 'Length'], ['onclick', () => (createTab('Length'))]]],"
    " 'navWeight': ['navList', 'li', [['textContent', 'Weight'], ['onclick', () => (createTab('Weight'))]]],"
    " 'navTemperature': ['navList', 'li', [['textContent', 'Temperature'], ['onclick', () => (createTab('Temperature'))]]],"
    " 'main': ['body', 'main']"
    " }, home);"
    " home.navLength.onclick();"
    " function createTab(t) {"
    " if(tabSelected === t) return;"
    " if(tabSelected !== '') home['nav' + tabSelected].classList.remove('tab_selected');"
    " tabSelected = t;"
    " home['nav' + tabSelected].classList.add('tab_selected');"
    " home.main.textContent = '';"
    " const tabMap = {"
    " 'enterUnit': ['main', 'p', [['textContent', 'Enter the ' + tabSelected + ' to Convert']]],"
    " 'enterUnitInp': ['main', 'input', [['type', 'number'], ['step', 'any'], ['oninput', () => (handleTab(tab))]]],"
    " 'unitFrom': ['main', 'p', [['textContent', 'Unit to Convert from']]],"
    " 'unitFromList': ['main', 'select', [['onchange', () => (handleTab(tab))]]],"
    " 'unitTo': ['main', 'p', [['textContent', 'Unit to Convert to']]],"
    " 'unitToList': ['main', 'select', [['onchange', () => (handleTab(tab))]]],"
    " 'submitArea': ['main', 'p'],"
    " 'submit': ['submitArea', 'button', [['textContent', 'Convert'], ['disabled', true]]],"
    " 'info': ['main', 'p', [['classList', 'error']]]"
    " };"
    " for(let item of units[tabSelected]) {"
    " tabMap['optFrom' + item[1]] = ['unitFromList', 'option', [['textContent', item[0]], ['value', item[1]]]];"
    " tabMap['optTo' + item[1]] = ['unitToList', 'option', [['textContent', item[0]], ['value', item[1]]]];"
    " }"
    " const tab = {'main': home.main};"
    " elemCreator(tabMap, tab);"
    " tab.enterUnitInp.value = inpValue;"
    " tab.unitFromList.value = '';"
    " tab.unitToList.value = '';"
    " }"
    " function handleTab(tab) {"
    " if(tab.enterUnitInp.value !== ''"
    " && (tabSelected === 'Temperature' || tab.enterUnitInp.value !== '0')"
    " && tab.unitFromList.value !== ''"
    " && tab.unitToList.value !== ''"
    " && tab.unitFromList.value !== tab.unitToList.value) {"
    " if(tab.submit.disabled) {"
    " tab.submit.disabled = false;"
    " tab.submit.onclick = () => (unitConverter(tab));"
    " }"
    " } else {"
    " if(!tab.submit.disabled) {"
    " tab.submit.disabled = true;"
    " tab.submit.onclick = null;"
    " }"
    " }"
    " if(tab.info.textContent !== '') {"
    " tab.info.textContent = '';"
    " }"
    " inpValue = tab.enterUnitInp.value;"
    " }"
    " function unitResult(result) {"
    " home.main.textContent = '';"
    " elemCreator({"
    " 'msg': ['main', 'p', [['textContent', 'Result of your calculation']]],"
    " 'result': ['main', 'div', [['classList', 'result'], ['textContent', result.original_value]]],"
    " 'valAbr': ['result', 'span', [['classList', 'result-abr'], ['textContent', result.unit_from]]],"
    " 'resVal': ['result', 'span', [['textContent', ' = ' + result.value]]],"
    " 'resAbr': ['result', 'span', [['classList', 'result-abr'], ['textContent', result.unit_to]]],"
    " 'reset': ['main', 'button', [['textContent', 'Reset'], ['onclick', resetTab]]]"
    " }, {}, home.main);"
    " }"
    " function resetTab() {"
    " const temp = tabSelected;"
    " inpValue = '';"
    " tabSelected = '';"
    " createTab(temp);"
    " }"
    " async function unitConverter(tab) {"
    " tab.submit.disabled = true;"
    " tab.submit.onclick = null;"
    " const json = {"
    " category: tabSelected,"
    " value: parseFloat(tab.enterUnitInp.value),"
    " unit_from: tab.unitFromList.value,"
    " unit_to: tab.unitToList.value"
    " };"
    " try {"
    " const result = await apiRequest('POST', '/api/unit-converter', json);"
    " result['unit_from'] = json.unit_from;"
    " result['unit_to'] = json.unit_to;"
    " result['original_value'] = json.value;"
    " unitResult(result);"
    " inpValue = '';"
    " } catch(err) {"
    " tab.info.textContent = await err;"
    " tab.submit.onclick = () => (unitConverter(tab));"
    " tab.submit.disabled = false;"
    " }"
    " }"
    " async function apiRequest(m, p, j) {"
    " const o = {method: m, credentials: 'include', headers: {}};"
    " if(j) {"
    " o.headers['Content-Type'] = 'application/json';"
    " o.body = JSON.stringify(j);"
    " }"
    " return await fetch(location.origin + p, o)"
    " .then(async r => {"
    " if(r.status >= 400) {"
    " const err = await r.json();"
    " return Promise.reject(err.message);"
    " }"
    " return r.json();"
    " }).catch(async err => {"
    " return Promise.reject(err);"
    " });"
    " }"
    " function elemCreator(m, o, t) {"
    " for(const e in m) {"
    " o[e] = document.createElement(m[e][1]);"
    " if(m[e][2]) {"
    " for(const a of m[e][2]) {"
    " if(a.length === 3) o[e][a[0]][a[1]] = a[2];"
    " else o[e][a[0]] = a[1];"
    " }"
    " }"
    " if(o[m[e][0]]) o[m[e][0]].appendChild(o[e]);"
    " else if(t && t[m[e][0]]) t[m[e][0]].appendChild(o[e]);"
    " else if(t) t.appendChild(o[e]);"
    " }"
    " }";
const char error_base_html[] =
    "<!DOCTYPE html>"
    " <html lang=\"en\">"
    " <head>"
    " <meta charset=\"UTF-8\">"
    " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    " <title>%d %s</title>"
    " <style>"
    " body {"
    " text-align: center;"
    " }"
    " </style>"
    " </head>"
    " <body>"
    " <h1>%s</h1>"
    " <p>%s</p>"
    " </body>"
    " </html>";
void handle_resource(client_header *header) {
    if(strcmp(header->path, "/favicon.ico") == 0) header->status_code = 404;
    if(header->status_code >= 400) {
        if(!header->status_msg) set_default_status_msg(header);
        set_formatted_string(&(header->body_response), error_base_html,
            header->status_code, get_status(header->status_code),
            get_status(header->status_code),
            header->status_msg);
        set_string(&(header->content_type), "text/html");
        send_response(header, header->body_response);
    } else if(strcmp(header->path, "/src/style.css") == 0) {
        set_string(&(header->content_type), "text/css");
        send_response(header, style);
    } else if(strcmp(header->path, "/src/script.js") == 0) {
        set_string(&(header->content_type), "text/javascript");
        send_response(header, script);
    } else {
        set_string(&(header->content_type), "text/html");
        send_response(header, home);
    }
}